//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyKurs_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class BundleSupplies
    {
        public int ID_Bundle { get; set; }
        public Nullable<int> ID_Supply { get; set; }
        public Nullable<int> ID_Supplier { get; set; }
    
        public virtual Supplier Supplier { get; set; }
        public virtual Supply Supply { get; set; }
    }
}
