//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PharmacyKurs_2
{
    using System;
    using System.Collections.Generic;
    
    public partial class Preparation
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Preparation()
        {
            this.Supply = new HashSet<Supply>();
        }
    
        public int ID_Preparation { get; set; }
        public Nullable<int> ID_Group { get; set; }
        public Nullable<int> ID_Supplier { get; set; }
        public string PreparationName { get; set; }
        public Nullable<int> Cost { get; set; }
        public string Product_picture { get; set; }
        public string Description { get; set; }
    
        public virtual Group Group { get; set; }
        public virtual Supplier Supplier { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Supply> Supply { get; set; }
    }
}
